services:
  minio:
    container_name: hls-vi-historical-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ".minio:/data"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 20s
      retries: 20
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    container_name: hls-vi-historical-mc
    image: quay.io/minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    entrypoint: >
      /bin/sh -c "
      set -ex;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/lp-prod-public;
      mc mb --ignore-existing myminio/lp-prod-protected;
      mc mb --ignore-existing myminio/hls-global-v2-forward;
      "

  cli:
    container_name: hls-vi-historical-cli
    build: .
    platform: linux/amd64
    depends_on:
      - mc
    environment:
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
      - AWS_BATCH_JOB_ID=42
      - OUTPUT_BUCKET=hls-global-v2-forward
